### ISSUE TITLE
Cloud Baza

### ISSUE THREAD

**Issue by C0mpy** [stefanplazic/testiranje_softvera#1]
Naci free cloud MySql bazu za razvoj projekta

**Comment by C0mpy** [comment]
Nasao sam neku na freemysqlhosting.net, jos samo da isprobam, 5MB dozvoljava

**Comment by C0mpy** [comment]
Ipak smo se na kraju odlucili za lokalne baze.

**Comment by Mijura** [comment]
Napraviti konekciju, sa sledecim podesavanjima:
Hostname: db4free.net
Port: 3306
Username: kts1234
Password: kts1234

**Comment by Mijura** [comment]
Ne vredi. Ipak treba koristiti lokalne baze, ova konekcija je uzasno spora...
