### ISSUE TITLE
Razmena poruka

### ISSUE THREAD

**Issue by C0mpy** [stefanplazic/testiranje_softvera#11]
Omoguciti kupcu slanje poruke zeljenom oglasavacu, a oglasavacu mogucnost da odgovori na poruke kupca.

**Comment by Mijura** [comment]
Ovo je podrzano preko preko notifikacija. #21

**Comment by Mijura** [comment]
Nigde ne postoji metoda koja omogucava oglasvacu/kupcu da posalje poruku.

**Comment by Mijura** [comment]
Postoji metoda saveNotification koja se odnosi na cuvanje poruka i informacija. Bolje bi bilo da se ta meroda razdvoji na dve sendMessage() i sendInfo()
