### ISSUE TITLE
Registrovanje Kompanije

### ISSUE THREAD

**Issue by C0mpy** [stefanplazic/testiranje_softvera#9]
Omoguciti oglasavacu registrovanje nove kompanije, a adminu mogucnost prihvatanja ili odbijanja registracije.

**Comment by Mijura** [comment]
napisan backend za registrovanje nove kompanije, ostalo prihvatanje i odbijanje od strane admina

**Comment by Mijura** [comment]
Prihvatanje i odbijanje registracije kompanije, moraće da sačeka dok se ne implementiraju notifikacije.
